config/routes.rb
Rails.application.routes.draw do
  
  root to: "rooms#index"
  
  devise_for :users, controllers: {
    registrations: "users/registrations",
    sessions: "users/sessions",
    omniauth_callbacks: "users/omniauth_callbacks"
  }
  resources :rooms
  resources :messages

  # normal search
  get "search", to: "rooms#index", as: "search"
  get "search/topic", to: "rooms#index", as: "search_topic"

  get "up" => "rails/health#show", as: :rails_health_check

  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

end

app/models/room.rb
class Room < ApplicationRecord
	validates :name, presence: { message: "should be present" }
	validates :topic_name, presence: { message: "should be present" }
	belongs_to :user
	belongs_to :topic
  	has_many :messages, dependent: :destroy
  	has_many :users, through: :messages


  	searchkick text_middle: %i[:name :description]

  	self.per_page = 5

	# before_save :set_topic_name
	attr_accessor :topic_name


	def host
		user = User.find(self.user_id)
	end

	def topic
		topic_name = Topic.find(self.topic_id)
	end



	# searchkick text_middle: %i[name description topic]


	# def set_topic_name
	# 	tmp = Topic.find_by_name(topic_name)
	# 	if tmp
	# 		self.topic_id = tmp.id
	# 	end
	# end

end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  
  def index
    # @rooms = Room.order(created_at: :desc)
    
    if params[:q].blank?
      @rooms = Room.paginate(page: params[:page]).order(created_at: :desc)
    else
      @search = Room.where("name LIKE ? or description LIKE ?", "%#{params[:q]}%", "%#{params[:q]}%").order(created_at: :desc)
      @rooms = @search.paginate(page: params[:page]).order(created_at: :desc)
    end

    unless params[:query].blank?
      @topics = Topic.where("name LIKE ?", "%#{params[:q]}%")
    end

  end
  
  def new
    @room = Room.new
  end

  def create
    @room = current_user.rooms.new(room_params)
    topic_name = params[:room][:topic_name].capitalize
    @room.name = @room.name.capitalize
    @topic = Topic.find_or_create_by(name: topic_name)
    @room.topic_id = @topic.id
    if @room.save
      redirect_to root_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @room = Room.find(params[:id])
    @messages = @room.messages.all
    # @participants = @room.users.uniq.count
  end



  

  private
  def room_params
    params.require(:room).permit(:topic_name, :name, :description, :topic_id)
  end
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/_activity.html.erb
<h5>Recent Activities</h5>

<% rooms.each do |room| %>
	<% if room.messages.any? %>
		<% room.messages.last(5).each do |message| %>
			<div class="rounded border mt-3 p-3">
				<span>@<%= message.user.username %></span>
				<span><%= time_ago_in_words(message.updated_at) %> ago replied in "<%= message.room.name %>"</span>
				<span class="bg-light"><%= message.body %></span>
			</div>
		<% end %>
	<% end %>

<% end %>

app/views/rooms/_rooms.html.erb
<% @rooms.each do |room| %>
	<div class="jumbotron shadow-sm rounded p-3 mt-4">
		<div class="row mb-2">
			<div class="col-md-6">
				<span>Created by @<%= room.host.username %></span>
			</div>
			<div class="col-md-6 m-auto">
				<span class="float-end"><%= time_ago_in_words(room.created_at) %> ago</span>
			</div>
		</div>
	  <h3 class="display-7"><%= link_to room.name, room %></h3>
	  <p class="lead"><%= room.description %></p>
	  <hr class="my-4">
	  <div class="row mb-2">
			<div class="col-md-6">
				<div class="my-2">
					<i class="fa-solid fa-user-group"></i><span class="mx-3"><%= room.users.uniq.count %> Joined</span>
				</div>
			</div>
			<div class="col-md-6 m-auto">
				<div class="bg-light px-3 py-1 float-end border rounded">
					<span><%= room.topic.name %></span>
				</div>
			</div>
		</div>
	  
	</div>
	
<% end %>
<div class="my-3">
	<%= will_paginate @rooms %>
</div>

app/views/rooms/_search.html.erb
<%= form_with(url: search_path, method: :get, class: "d-flex ms-auto") do |form| %>
        <%= form.text_field :q, class: "form-control", placeholder: "Search rooms..." %>
<% end %>

app/views/rooms/_topics.html.erb
<h5>Browse topics</h5>

<% if Topic.any? %>

  <ul class="list-group">

    <li class="">
      <%= link_to 'All', root_path %>
      <span class=""><%= Topic.all.count %></span>
    </li>

    <% Topic.last(5).each do |topic| %>

      <li class="">
        <%= link_to topic.name, "#{root_path}?q=#{topic.name}" %>
        <span class=""><%= topic.rooms.all.count %></span>
      </li>

    <% end %>

    <li>
      <button style="padding:0;" type="button" class="btn btn-link" data-bs-toggle="modal" data-bs-target="#topicsModal">
        More
      </button>

      <div class="modal fade" id="topicsModal" tabindex="-1" role="dialog" aria-labelledby="topicsModalLabel" aria-hidden="true">
        
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="topicsModalLabel">Browse topics</h5>
          </div>
          <div class="modal-body">
            <%= form_with(url: search_topic_path, method: :get, class: "d-flex ms-auto") do |form| %>
              <%= form.text_field :query, class: "form-control", placeholder: "Search topics..." %>
            <% end %>

            <ul>
              <li>
                <%= link_to 'All', root_path %>
                <span class=""><%= Topic.all.count %></span>
              </li>
              <li>
                <%= link_to 'All', root_path %>
                <span class=""><%= Topic.all.count %></span>
              </li>

            </ul>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
            <button type="button" class="btn btn-primary">Save changes</button>
          </div>
        </div>
      </div>
      </div>
    </li>
  </ul>
<% else %>
  <p>No topic found</p>
<% end %>

app/views/rooms/index.html.erb
<div data-controller="rooms" class="row mt-5">
	<div class="col-md-2"><%= render "topics" %></div>

	<div class="col-md-7">
		<div class="row">
			<div class="col-md-6">
				<h6>Study rooms</h6>
				<span><%= pluralize(@rooms.all.count, 'room') %> available</span>
			</div>
			<div class="col-md-6 m-auto">
				<%= link_to "Create room", new_room_path, class: "btn btn-outline-primary float-end" %>
			</div>
		</div>

		<%= render "rooms", rooms: @rooms %>

	</div>

	<div class="col-md-3">
		<%= render "activity", rooms: @rooms %>
	</div>
</div>

app/views/rooms/new.html.erb
<h1>Create room</h1>
<% @room.errors.full_messages.each do |message| %>
   		<%= message %>
<% end %>
<%= form_with model: @room do |form| %>
  
  <div>
    <%= form.label :topic_name %>
    <%= form.text_field :topic_name %>  
  </div>

  <div>
  	<%= form.label :name %>
  	<%= form.text_field :name %>	
  </div>

  <div>
  	<%= form.label :description %>
  	<%= form.text_field :description %>	
  </div>

  <%= form.submit %>
  
<% end %>

app/views/rooms/show.html.erb
<div id="room-id" data-room-id="<%= @room.try(:id) %>"></div>
<div style="margin: 15px 0;">
  Room name: <%= @room.name %><br>
  Room description: <%= @room.description %><br>
  Topic name: <%= @room.topic.name %>---<%= @room.topic.id %><br>
  Host: <%= @room.host.username %><br>
</div>


<hr>
<div style="display: flex;">

  <div style="width:60%">
    <h3>Messages</h3>
    <div id="messages">
    <% @messages.each do |message| %>
      <%= render "messages/message", message: message %>
    <% end %>
    </div>

    <div>
      <% if current_user %>
        <%= render 'messages/form', message: Message.new, room: @room %>
      <% end %>
    </div>



    <% unless current_user %>
      <%= link_to "Want to join this room?", user_session_path %>
    <% end %>
  </div>

  <div style="width: 40%">
    Participants
  </div>
</div>